-- ============================================================================
-- Supabase PostgreSQL Schema & Security RLS Policies
-- Developer: Ephraim Kumar
-- Title: Java & Python Learner | Aspiring Software Engineer
-- ============================================================================

-- Drop existing tables if re-initializing schema
DROP TABLE IF EXISTS admin_users CASCADE;
DROP TABLE IF EXISTS contacts CASCADE;
DROP TABLE IF EXISTS achievements CASCADE;
DROP TABLE IF EXISTS skills CASCADE;
DROP TABLE IF EXISTS projects CASCADE;

-- ----------------------------------------------------------------------------
-- 1. PROJECTS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    technologies TEXT[] NOT NULL,
    github_url TEXT DEFAULT '',
    live_url TEXT DEFAULT '',
    image_url TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Public read access
CREATE POLICY "Public Read Access for Projects"
    ON projects FOR SELECT
    USING (true);

-- RLS Policy: Admin full access
CREATE POLICY "Admin Full Access for Projects"
    ON projects FOR ALL
    USING (
        auth.uid() IN (SELECT user_id FROM admin_users)
    );

-- ----------------------------------------------------------------------------
-- 2. SKILLS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL, -- 'Programming', 'Backend', 'Database', 'Tools'
    level TEXT NOT NULL DEFAULT 'Learning', -- 'Learning', 'Basic / Learning', ''
    icon TEXT DEFAULT '',
    display_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE skills ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Public read access
CREATE POLICY "Public Read Access for Skills"
    ON skills FOR SELECT
    USING (true);

-- RLS Policy: Admin full access
CREATE POLICY "Admin Full Access for Skills"
    ON skills FOR ALL
    USING (
        auth.uid() IN (SELECT user_id FROM admin_users)
    );

-- ----------------------------------------------------------------------------
-- 3. ACHIEVEMENTS & CERTIFICATIONS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS achievements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    issuer TEXT DEFAULT '',
    date TEXT DEFAULT '',
    category TEXT DEFAULT 'Achievement', -- 'Achievement' or 'Certification'
    certificate_url TEXT DEFAULT '',
    image_url TEXT DEFAULT '',
    external_url TEXT DEFAULT '',
    display_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Public read access
CREATE POLICY "Public Read Access for Achievements"
    ON achievements FOR SELECT
    USING (true);

-- RLS Policy: Admin full access
CREATE POLICY "Admin Full Access for Achievements"
    ON achievements FOR ALL
    USING (
        auth.uid() IN (SELECT user_id FROM admin_users)
    );

-- ----------------------------------------------------------------------------
-- 4. CONTACTS TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Public insert access for contact form
CREATE POLICY "Public Insert Access for Contacts"
    ON contacts FOR INSERT
    WITH CHECK (true);

-- RLS Policy: Admin read/delete access only
CREATE POLICY "Admin Access for Contacts"
    ON contacts FOR ALL
    USING (
        auth.uid() IN (SELECT user_id FROM admin_users)
    );

-- ----------------------------------------------------------------------------
-- 5. ADMIN USERS AUTHORIZATION TABLE
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL UNIQUE, -- References auth.users(id) in Supabase Auth
    email TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Admin self-read access
CREATE POLICY "Admin Read Self"
    ON admin_users FOR SELECT
    USING (
        auth.uid() = user_id
    );

-- ----------------------------------------------------------------------------
-- 6. SEED DATA - ACCURATE USER DATA ONLY
-- ----------------------------------------------------------------------------

-- Seed Real Project: Flute-notation
INSERT INTO projects (title, description, technologies, github_url, live_url, image_url) VALUES
(
    'Flute-notation',
    'A user-friendly flute notation website for searching and learning flute notations of popular Telugu songs, with lyrics and corresponding notes in an easy-to-follow format.',
    ARRAY['HTML', 'CSS', 'JavaScript'],
    'https://github.com/EphraimkumarRacheti/Flute-notation',
    '',
    'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80'
);

-- Seed Exact Skills (Only Ephraim Kumar's specified skills)
INSERT INTO skills (name, category, level, icon, display_order) VALUES
-- Programming Languages
('Java', 'Programming', 'Learning', 'fa-solid fa-mug-hot', 1),
('Python', 'Programming', 'Learning', 'fa-brands fa-python', 2),
('C', 'Programming', 'Basic / Learning', 'fa-solid fa-terminal', 3),

-- Backend Technologies
('Flask', 'Backend', 'Learning', 'fa-solid fa-flask', 4),
('Spring Boot', 'Backend', 'Learning', 'fa-solid fa-leaf', 5),

-- Database Systems
('PostgreSQL', 'Database', 'Learning', 'fa-solid fa-database', 6),
('Supabase', 'Database', 'Learning', 'fa-solid fa-bolt', 7),

-- Developer Tools
('Git', 'Tools', 'Learning', 'fa-brands fa-git-alt', 8),
('GitHub', 'Tools', 'Learning', 'fa-brands fa-github', 9),
('VS Code', 'Tools', 'Tool', 'fa-solid fa-code', 10);

-- Seed Achievements & Certifications
INSERT INTO achievements (title, description, issuer, category, date, certificate_url, image_url, external_url, display_order) VALUES
(
    'Shastra 4.0 Level 1 Coding Challenge',
    'Achieved Runner-Up (3rd Prize) in Shastra 4.0 Level 1, a coding challenge conducted by Ramachandra College of Engineering, Eluru. Focused on algorithm design and logical problem-solving.',
    'Ramachandra College of Engineering',
    'Achievement',
    'April 2026',
    '',
    'https://media.licdn.com/dms/image/v2/D5622AQF4fGqWTVgmBA/feedshare-image-high-res/B56Z1_lvR4J8AU-/0/1775962093073?e=2147483647&v=beta&t=M4gvEPzOQn4xdYHf4jxlek0hAnch6cEE3CdGgLy7wbk',
    'https://lnkd.in/p/dPkPeBTs',
    1
),
(
    'Java Certification',
    'Successfully completed a Java Certification from Simplilearn. The certification helped strengthen my understanding of Java programming and improve my programming and problem-solving skills.',
    'Simplilearn',
    'Certification',
    '',
    '',
    '/static/images/java-certification.jpg',
    'https://lnkd.in/p/dY8ZfDEa',
    2
);


